Feature/arrays
Hitin/study-1 pull request #1
Opened 2019-10-17 18:31 UTC by Hitin

Выполнил 2 задания. С поиском не использовал стандартный метод index.

2019-10-17 19:09 UTC, Andrew8xx8 requested changes

2019-10-17 19:09 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        maxValue = array.max
Нужно самомому реализовать максимум

2019-10-22 08:52 UTC, Andrew8xx8 requested changes

2019-10-22 08:52 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        _array.each_with_index {|val, ind| res = ind if (val == _query)}
Нужно реализовать бинарный поиск. Это не бинарный поиск

https://ru.wikipedia.org/wiki/%D0%94%D0%B2%D0%BE%D0%B8%D1%87%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA

2019-10-22 18:40 UTC, Hitin commented on test/exercise/arrays/solution.rb
> +        _array.each_with_index {|val, ind| res = ind if (val == _query)}
Сделал бинарный поиск

2019-10-30 12:31 UTC, artempartos requested changes

2019-10-30 12:31 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        maxValue = array[0];
camelcaыe не ииспользуется в руби
max_value

2019-10-30 12:31 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        array.each {|val| val > 0 ? result << maxValue : result << val}
реализуй с использованием map

2019-10-30 12:31 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        res = -1;
попробуй реализовать в рекурсиивном стиле

2019-10-30 17:12 UTC, Hitin commented on test/exercise/arrays/solution.rb
> +        #array.each {|val| max_value = val if (val > max_value)}.map{|val| val > 0 ? max_value : val}
Скажи, как предпочтительней делать? Вроде бы в 1 строку интересней но теряется читаемость

2019-10-30 17:12 UTC, Hitin commented on test/exercise/arrays/solution.rb
> +        #return _array[middle] < _query ? self.search(_array, _query, middle, last) : self.search(_array, _query, first, middle) if interval > 1
Аналогичная ситуация. В такой записи можно и не заметить if в конце

2019-10-30 17:15 UTC, Hitin commented on test/exercise/arrays/solution.rb
> +        array.each {|val| val > 0 ? result << maxValue : result << val}
Реализовал

2019-11-14 10:05 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        #return _array[middle] < _query ? self.search(_array, _query, middle, last) : self.search(_array, _query, first, middle) if interval > 1
Всегда лучше в несколько строк

2019-11-14 10:05 UTC, Andrew8xx8 approved these changes

2019-11-14 10:16 UTC, closed without merging