Feature/fp
Hitin/study-1 pull request #2
Opened 2019-10-19 16:12 UTC by Hitin

Выполнил 2 задания с использованием map и reduce.

2019-10-22 08:56 UTC, Andrew8xx8 requested changes

2019-10-22 08:56 UTC, Andrew8xx8 commented on test/exercise/fp/solution.rb
> +        result = _array.map { |film| film["rating_kinopoisk"].to_f if (!film["country"].nil? && film["country"].split(',').size > 1 && film["rating_kinopoisk"].to_f > 0) }.compact
Как правило в руби к каждому логическому методу есть противоположный. В этом смысле для восприятия проще проверить что что-то есть, чем что отрицание того что чего-то нет.
`!film["country"].nil?` -> `film["country"].present?`

2019-10-22 19:02 UTC, Hitin commented on test/exercise/fp/solution.rb
> +        result = _array.map { |film| film["rating_kinopoisk"].to_f if (!film["country"].nil? && film["country"].split(',').size > 1 && film["rating_kinopoisk"].to_f > 0) }.compact
Насколько я понял из документации метод present? предоставляет Rails. В руби же для объекта NilClass нет данного метода и поэтому когда я изменяю на present? пишет ошибку undefined method `present?' for nil:NilClass. Поправь меня если я не прав?

2019-10-30 12:31 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        result = _array.map { |film| film["rating_kinopoisk"].to_f if (!film["country"].nil? && film["country"].split(',').size > 1 && film["rating_kinopoisk"].to_f > 0) }.compact
все правильно, тут нет рельс

2019-10-30 12:32 UTC, artempartos commented
👍

2019-10-30 14:46 UTC, closed without merging