My rackup
Hitin/study-1 pull request #4
Opened 2019-11-04 11:13 UTC by Hitin

Моя версия Inatra.

2019-11-14 10:05 UTC, Andrew8xx8 requested changes

2019-11-14 10:05 UTC, Andrew8xx8 commented on test/exercise/rackup/inatra.rb
> +
Нужно еще реализовать другие методы HTTP

2019-11-14 12:06 UTC, artempartos requested changes

2019-11-14 12:06 UTC, artempartos commented on test/exercise/rackup/test.rb
>        browser.get '/hello'
напги тест на post /hello с другим ответом

2019-11-15 12:49 UTC, artempartos commented
👍

2019-11-18 05:28 UTC, closed without merging